-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.usuario
(
    idusuario serial NOT NULL,
    nome text NOT NULL,
    login text NOT NULL,
    senha text NOT NULL,
    ativo integer,
    PRIMARY KEY (idusuario)
);

CREATE TABLE public.pontoturistico
(
    idpontoturistico serial NOT NULL,
    criador_idusuario integer NOT NULL,
    descricao text NOT NULL,
    nome text NOT NULL,
    avaliacao integer NOT NULL,
    localizacao text NOT NULL,
    preco double precision NOT NULL,
    tempo time without time zone NOT NULL,
    quando timestamp without time zone NOT NULL,
    latitude text NOT NULL,
    longitude text NOT NULL,
    foto text NOT NULL,
    foto_nome text NOT NULL,
    foto_tipo text NOT NULL,
    PRIMARY KEY (idpontoturistico)
);

CREATE TABLE public.roteiro
(
    idroteiro serial NOT NULL,
    usuario_idusuario integer NOT NULL,
    data timestamp without time zone NOT NULL,
    PRIMARY KEY (idroteiro)
);

CREATE TABLE public.contem
(
    roteiro_idroteiro serial NOT NULL,
    pontoturistico_idpontoturistico serial NOT NULL
);

ALTER TABLE public.pontoturistico
    ADD FOREIGN KEY (criador_idusuario)
    REFERENCES public.usuario (idusuario)
    NOT VALID;


ALTER TABLE public.roteiro
    ADD FOREIGN KEY (usuario_idusuario)
    REFERENCES public.usuario (idusuario)
    NOT VALID;


ALTER TABLE public.contem
    ADD FOREIGN KEY (roteiro_idroteiro)
    REFERENCES public.roteiro (idroteiro)
    NOT VALID;


ALTER TABLE public.contem
    ADD FOREIGN KEY (pontoturistico_idpontoturistico)
    REFERENCES public.pontoturistico (idpontoturistico)
    NOT VALID;

END;